package cudnn

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/* WAS Generated by gencudnn. DO NOT EDIT */

// #include <stdint.h>
// #include <cudnn.h>
import "C"
import "runtime"

// TensorTransform is a representation of cudnnTensorTransformDescriptor_t.
type TensorTransform struct {
	internal C.cudnnTensorTransformDescriptor_t

	nbDims     uint32
	destFormat TensorFormat
	padBeforeA []int32
	padAfterA  []int32
	foldA      []uint32
	direction  FoldingDirection
}

// NewTensorTransform creates a new TensorTransform.
func NewTensorTransform(nbDims uint32, destFormat TensorFormat, padBeforeA []int32, padAfterA []int32, foldA []uint32, direction FoldingDirection) (retVal *TensorTransform, err error) {
	var internal C.cudnnTensorTransformDescriptor_t
	if err := result(C.cudnnCreateTensorTransformDescriptor(&internal)); err != nil {
		return nil, err
	}

	padBeforeAC := int32s2CInt32Ptr(padBeforeA)
	padAfterAC := int32s2CInt32Ptr(padAfterA)
	foldAC := uint32s2CUint32Ptr(foldA)

	if err := result(C.cudnnSetTensorTransformDescriptor(internal, C.uint32_t(nbDims), destFormat.C(), padBeforeAC, padAfterAC, foldAC, direction.C())); err != nil {
		return nil, err
	}

	retVal = &TensorTransform{
		internal:   internal,
		nbDims:     nbDims,
		destFormat: destFormat,
		padBeforeA: padBeforeA,
		padAfterA:  padAfterA,
		foldA:      foldA,
		direction:  direction,
	}
	runtime.SetFinalizer(retVal, destroyTensorTransform)
	return retVal, nil
}

// C returns the cgo representation
func (t *TensorTransform) C() C.cudnnTensorTransformDescriptor_t { return t.internal }

func (t *TensorTransform) NDims() uint32 { return t.nbDims }

// DestFormat returns the internal destFormat.
func (t *TensorTransform) DestFormat() TensorFormat { return t.destFormat }

// PadBeforeA returns the internal `padBeforeA` padding slice.
func (t *TensorTransform) PadBeforeA() []int32 { return t.padBeforeA }

// PadAfterA returns the internal `padAfterA` padding slice.
func (t *TensorTransform) PadAfterA() []int32 { return t.padAfterA }

// FoldA returns the internal `foldA` slice.
func (t *TensorTransform) FoldA() []uint32 { return t.foldA }

// Direction returns the internal direction.
func (t *TensorTransform) Direction() FoldingDirection { return t.direction }

func destroyTensorTransform(obj *TensorTransform) {
	C.cudnnDestroyTensorTransformDescriptor(obj.internal)
}
