package cudnn

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/* WAS Generated by gencudnn. DO NOT EDIT */

// #include <cudnn.h>
import "C"
import (
	"runtime"
	"unsafe"
)

// FusedOpVariantParams is a representation of cudnnFusedOpsVariantParamPack_t.
type FusedOpVariantParams struct {
	internal C.cudnnFusedOpsVariantParamPack_t

	ops        FusedOps
	paramLabel FusedOpsVariantParamLabel
	ptr        Memory
}

// NewFusedOpVariantParams creates a new FusedOpVariantParams.
func NewFusedOpVariantParams(ops FusedOps, paramLabel FusedOpsVariantParamLabel, ptr Memory) (retVal *FusedOpVariantParams, err error) {
	var internal C.cudnnFusedOpsVariantParamPack_t
	if err := result(C.cudnnCreateFusedOpsVariantParamPack(&internal, ops.C())); err != nil {
		return nil, err
	}

	if err := result(C.cudnnSetFusedOpsVariantParamPackAttribute(internal, paramLabel.C(), unsafe.Pointer(ptr.Uintptr()))); err != nil {
		return nil, err
	}

	retVal = &FusedOpVariantParams{
		internal:   internal,
		paramLabel: paramLabel,
		ptr:        ptr,
		ops:        ops,
	}
	runtime.SetFinalizer(retVal, destroyFusedOpVariantParams)
	return retVal, nil
}

// C returns the internal cgo representation.
func (f *FusedOpVariantParams) C() C.cudnnFusedOpsVariantParamPack_t { return f.internal }

// Ops returns the ops that are fused.
func (f *FusedOpVariantParams) Ops() FusedOps { return f.ops }

// ParamLabel returns the internal paramLabel.
func (f *FusedOpVariantParams) ParamLabel() FusedOpsVariantParamLabel { return f.paramLabel }

// Ptr returns the internal ptr.
func (f *FusedOpVariantParams) Ptr() Memory { return f.ptr }

func destroyFusedOpVariantParams(obj *FusedOpVariantParams) {
	C.cudnnDestroyFusedOpsVariantParamPack(obj.internal)
}
