package main

// Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

const header = `package cu

// #include <cuda.h>
import "C"

// This file was generated by the Bhojpur Neuron (genlib) program. DO NOT EDIT

`

const resultHeader = `package cu

//#include <cuda.h>
import "C"
import "fmt"

// This file was generated by the Bhojpur Neuron (genlib) program. DO NOT EDIT

// cuResult is the Go version of CUresult:
// http://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1gc6c391505e117393cc2558fff6bfc2e9
type cuResult int

func (err cuResult) Error() string  { return err.String() }
func (err cuResult) String() string {
    if msg, ok := resString[err]; ok {
        return msg
    }
    return fmt.Sprintf("UnknownErrorCode:%d", err)
}

func result(x C.CUresult) error {
	err := cuResult(x)
	if err == Success {
		return nil
	}
	return err
}

`
