// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import "strconv"

type Triangle int32

const (
	TriangleNOT_TRIANGLE Triangle = 0
	TriangleUPPER        Triangle = 1
	TriangleLOWER        Triangle = 2
	TriangleSYMMETRIC    Triangle = 3
)

var EnumNamesTriangle = map[Triangle]string{
	TriangleNOT_TRIANGLE: "NOT_TRIANGLE",
	TriangleUPPER:        "UPPER",
	TriangleLOWER:        "LOWER",
	TriangleSYMMETRIC:    "SYMMETRIC",
}

var EnumValuesTriangle = map[string]Triangle{
	"NOT_TRIANGLE": TriangleNOT_TRIANGLE,
	"UPPER":        TriangleUPPER,
	"LOWER":        TriangleLOWER,
	"SYMMETRIC":    TriangleSYMMETRIC,
}

func (v Triangle) String() string {
	if s, ok := EnumNamesTriangle[v]; ok {
		return s
	}
	return "Triangle(" + strconv.FormatInt(int64(v), 10) + ")"
}
